### ISSUE TITLE
key listeners attached at run-time

### ISSUE THREAD

**Issue by bantic** [dollarshaveclub/ember-responds-to#3]
The code that adds the 'keydown' listeners (in [responds-to-enter-keydown](https://github.com/dollarshaveclub/ember-responds-to/blob/master/addon/mixins/responds-to-enter-keydown.js#L8-L14) and [responds-to-esc-keydown](https://github.com/dollarshaveclub/ember-responds-to/blob/master/addon/mixins/responds-to-esc-keydown.js#L9-L16)) is run when those modules are evaluated rather than when their mixins are used. Therefore these listeners will be added to the browser window even if the `responds-to-esc-keydown` and `responds-to-enter-keydown` mixins are never mixed into any components. In addition, the listeners are never removed, which can create memory leaks (the closure to the module context will never be garbage collected).

Perhaps the event listeners should be attached in the `didInsertElement` method if necessary, and removed in `willDestroyElement` if there are no remaining listeners, like so:

```
...
function addKeydownListener() {
  Ember.$(window).on('keydown', ...);
}

export default Ember.Mixin.create({
  didInsertElement() {
    if (listeners.length === 0) {
      addKeydownListener();
    }
    listeners.unshift(this);
  },
  willDestroyElement() {
    listeners = listeners.filter(listener => listener !== this);
    if (listeners.length === 0) {
      Ember.$(window).off('keydown', ...);
    }
  }
});
```

**Comment by pwfisher** [comment]
If the mixins are never mixed into any component, they should not be part of the payload on the client, right? If you mean "never used" as in never instantiated, then yes, it is ever so slightly suboptimal.

Since our Ember app code is evaluated once per page load, there is a small constant cost. This doesn‘t grow, so it‘s not a leak.

Your code looks like it would work fine and would be a small optimization in some cases, but I'd also like to keep things as simple as possible. The beauty of this addon is that it's so damn simple. 

I'm inclined to pass on this microöptimization for the sake of clarity.

**Comment by bantic** [comment]
@pwfisher Yeah, the listeners would only get added if the `import RespondsToX` are evaluated, which seems very unlikely to happen unless the imports are also mixed in.

The un-removed key listeners seems potentially problematic, like the sort of thing that could cause mysterious test failures down the line. I just wanted to raise this as a potential issue, but sounds like you've thought it through.
